trigger:
- master

jobs:
- job: 'Model_Zoo_Win'
  pool:
    vmImage: 'windows-2019'
  strategy:
    matrix:
      py37:
        python.version: '3.7'
        onnx.version: '1.7'
    maxParallel: 2

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
    displayName: Add conda to PATH

  - script: conda create --yes --quiet --name py$(python.version) -c conda-forge python=$(python.version) numpy protobuf
    displayName: Create Anaconda environment

  - script: |
      call activate py$(python.version)
      python -m pip install onnx==$(onnx.version) requests
      python .azure-pipelines/test_models.py
    displayName: Install dependencies and test ONNX models
