name: Validate created ONNX model from mlagility

on:
  push:
    branches: [ main, new-models]
  pull_request:
    branches: [ main, new-models]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8']

    steps:
      - uses: actions/checkout@v3
        name: Checkout repo
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          activate-environment: mla
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies and mlagility
        run: |
          python -m pip install --upgrade pip
          git clone https://github.com/groq/mlagility.git
          cd mlagility
          pip install -r models/requirements.txt
          pip install -e .

      - name: Validate created ONNX model from mlagility
        run: |
          # TODO: remove the following after mlagility has resovled version contradict issue
          pip install -r models/mlagility/requirements.txt
          python workflow_scripts/run_mlagility.py --drop
